# Cargo network hardening (repo-scoped)
[http]
check-revoke = false
multiplexing = false

[net]
retry = 5
git-fetch-with-cli = true

# Vendoring switch (enable only after `cargo vendor` creates ./vendor/index)
# [source.crates-io]
# replace-with = "vendored-sparse"
#
# [source.vendored-sparse]
# registry = "sparse+file://vendor/index"