# Cargo network hardening (repo-scoped)
[http]
check-revoke = false
multiplexing = false

[net]
retry = 5
git-fetch-with-cli = true

# Vendoring switch (enable only after `cargo vendor` creates ./vendor/index)
# Enable ONLY AFTER ./vendor exists (see scripts/vendor-crates.ps1):
# [source.crates-io]
# replace-with = "vendored-sources"
#
# [source.vendored-sources]
# directory = "vendor"