# ---- Cargo network hardening (scoped to this repo) ----
[http]
check-revoke = false            # already needed on some Windows networks
multiplexing = false            # avoid HTTP/2 multiplexing on flaky proxies

[net]
retry = 5                       # re-try failed downloads
git-fetch-with-cli = true       # let git.exe handle TLS/proxy rules

[source.crates-io]
replace-with = "crates-io"

# When vendored/, we will switch replace-with to 'vendored-sparse'.

# ---- Vendoring (optional, after running scripts/vendor-crates.ps1) ----
# [source.vendored-sparse]
# registry = "sparse+file://vendor/index"